<?php
/**
 * @file
 * mio_menu.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function mio_menu_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: main-menu_0-12-mesi:taxonomy/term/27.
  $menu_links['main-menu_0-12-mesi:taxonomy/term/27'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/27',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '0-12 mesi',
    'options' => array(
      'identifier' => 'main-menu_0-12-mesi:taxonomy/term/27',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_figli:taxonomy/term/8/all',
  );
  // Exported menu link: main-menu_1-3-anni:taxonomy/term/28.
  $menu_links['main-menu_1-3-anni:taxonomy/term/28'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/28',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '1-3 anni',
    'options' => array(
      'identifier' => 'main-menu_1-3-anni:taxonomy/term/28',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_figli:taxonomy/term/8/all',
  );
  // Exported menu link: main-menu_3-5-anni:taxonomy/term/29.
  $menu_links['main-menu_3-5-anni:taxonomy/term/29'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/29',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '3-5 anni',
    'options' => array(
      'identifier' => 'main-menu_3-5-anni:taxonomy/term/29',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_figli:taxonomy/term/8/all',
  );
  // Exported menu link: main-menu_6-10-anni:taxonomy/term/30.
  $menu_links['main-menu_6-10-anni:taxonomy/term/30'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/30',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '6-10 anni',
    'options' => array(
      'identifier' => 'main-menu_6-10-anni:taxonomy/term/30',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_figli:taxonomy/term/8/all',
  );
  // Exported menu link: main-menu_adolescenza:taxonomy/term/26.
  $menu_links['main-menu_adolescenza:taxonomy/term/26'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/26',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'adolescenza',
    'options' => array(
      'identifier' => 'main-menu_adolescenza:taxonomy/term/26',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_figli:taxonomy/term/8/all',
  );
  // Exported menu link: main-menu_adozione:taxonomy/term/9.
  $menu_links['main-menu_adozione:taxonomy/term/9'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/9',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'adozione',
    'options' => array(
      'identifier' => 'main-menu_adozione:taxonomy/term/9',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_famiglia:taxonomy/term/13/all',
  );
  // Exported menu link: main-menu_alimentazione:taxonomy/term/387.
  $menu_links['main-menu_alimentazione:taxonomy/term/387'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/387',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'alimentazione',
    'options' => array(
      'identifier' => 'main-menu_alimentazione:taxonomy/term/387',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_famiglia:taxonomy/term/13/all',
  );
  // Exported menu link: main-menu_allattamento:taxonomy/term/4.
  $menu_links['main-menu_allattamento:taxonomy/term/4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/4',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'allattamento',
    'options' => array(
      'identifier' => 'main-menu_allattamento:taxonomy/term/4',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_mamma:taxonomy/term/1/all',
  );
  // Exported menu link: main-menu_archivio-moda:taxonomy/term/699.
  $menu_links['main-menu_archivio-moda:taxonomy/term/699'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/699',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'archivio moda',
    'options' => array(
      'identifier' => 'main-menu_archivio-moda:taxonomy/term/699',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_moda:taxonomy/term/6',
  );
  // Exported menu link: main-menu_argomenti:<nolink>.
  $menu_links['main-menu_argomenti:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'ARGOMENTI',
    'options' => array(
      'link_icon' => '',
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'main-menu_argomenti:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
  );
  // Exported menu link: main-menu_bambino:taxonomy/term/24.
  $menu_links['main-menu_bambino:taxonomy/term/24'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/24',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'bambino',
    'options' => array(
      'identifier' => 'main-menu_bambino:taxonomy/term/24',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_salute:taxonomy/term/21/all',
  );
  // Exported menu link: main-menu_bellezza:taxonomy/term/7.
  $menu_links['main-menu_bellezza:taxonomy/term/7'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/7',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'bellezza',
    'options' => array(
      'identifier' => 'main-menu_bellezza:taxonomy/term/7',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_donna:taxonomy/term/5/all',
  );
  // Exported menu link: main-menu_blog:blog.
  $menu_links['main-menu_blog:blog'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'blog',
    'router_path' => 'blog',
    'link_title' => 'BLOG',
    'options' => array(
      'link_icon' => '',
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'main-menu_blog:blog',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: main-menu_calendario-dellavvento:http://www.mammeonline.net/content/calendario-dellavvento-mamme-bambini.
  $menu_links['main-menu_calendario-dellavvento:http://www.mammeonline.net/content/calendario-dellavvento-mamme-bambini'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'http://www.mammeonline.net/content/calendario-dellavvento-mamme-bambini',
    'router_path' => '',
    'link_title' => 'Calendario dell\'Avvento',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_calendario-dellavvento:http://www.mammeonline.net/content/calendario-dellavvento-mamme-bambini',
    ),
    'module' => 'menu',
    'hidden' => 1,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_speciale-natale:taxonomy/term/105',
  );
  // Exported menu link: main-menu_casa:taxonomy/term/17.
  $menu_links['main-menu_casa:taxonomy/term/17'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/17',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'casa',
    'options' => array(
      'identifier' => 'main-menu_casa:taxonomy/term/17',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_famiglia:taxonomy/term/13/all',
  );
  // Exported menu link: main-menu_cerca:search.
  $menu_links['main-menu_cerca:search'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'search',
    'router_path' => 'search',
    'link_title' => 'CERCA',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_cerca:search',
    ),
    'module' => 'menu',
    'hidden' => 1,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -38,
    'customized' => 1,
  );
  // Exported menu link: main-menu_chi-siamo:node/220.
  $menu_links['main-menu_chi-siamo:node/220'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/220',
    'router_path' => 'node/%',
    'link_title' => 'CHI SIAMO',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'main-menu_chi-siamo:node/220',
    ),
    'module' => 'menu',
    'hidden' => 1,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -45,
    'customized' => 1,
  );
  // Exported menu link: main-menu_compleanni:taxonomy/term/676.
  $menu_links['main-menu_compleanni:taxonomy/term/676'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/676',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'compleanni',
    'options' => array(
      'identifier' => 'main-menu_compleanni:taxonomy/term/676',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_festivit:taxonomy/term/104',
  );
  // Exported menu link: main-menu_contatto:contact.
  $menu_links['main-menu_contatto:contact'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'contact',
    'router_path' => 'contact',
    'link_title' => 'CONTATTO',
    'options' => array(
      'attributes' => array(
        'title' => 'modulo di contatto',
      ),
      'identifier' => 'main-menu_contatto:contact',
    ),
    'module' => 'menu',
    'hidden' => 1,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
  );
  // Exported menu link: main-menu_coppia:taxonomy/term/15.
  $menu_links['main-menu_coppia:taxonomy/term/15'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/15',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'coppia',
    'options' => array(
      'identifier' => 'main-menu_coppia:taxonomy/term/15',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_famiglia:taxonomy/term/13/all',
  );
  // Exported menu link: main-menu_creativit-natale:taxonomy/term/1543.
  $menu_links['main-menu_creativit-natale:taxonomy/term/1543'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/1543',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Creatività Natale',
    'options' => array(
      'identifier' => 'main-menu_creativit-natale:taxonomy/term/1543',
    ),
    'module' => 'menu',
    'hidden' => 1,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_speciale-natale:taxonomy/term/105',
  );
  // Exported menu link: main-menu_creativit:taxonomy/term/223.
  $menu_links['main-menu_creativit:taxonomy/term/223'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/223',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'creatività',
    'options' => array(
      'identifier' => 'main-menu_creativit:taxonomy/term/223',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_figli:taxonomy/term/8/all',
  );
  // Exported menu link: main-menu_cucina-in-festa:http://cuciniamo.mammeonline.net/category/tematiche/natale/.
  $menu_links['main-menu_cucina-in-festa:http://cuciniamo.mammeonline.net/category/tematiche/natale/'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'http://cuciniamo.mammeonline.net/category/tematiche/natale/',
    'router_path' => '',
    'link_title' => 'Cucina in festa',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_cucina-in-festa:http://cuciniamo.mammeonline.net/category/tematiche/natale/',
    ),
    'module' => 'menu',
    'hidden' => 1,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_speciale-natale:taxonomy/term/105',
  );
  // Exported menu link: main-menu_cucina:taxonomy/term/31.
  $menu_links['main-menu_cucina:taxonomy/term/31'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/31',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'cucina',
    'options' => array(
      'identifier' => 'main-menu_cucina:taxonomy/term/31',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_famiglia:taxonomy/term/13/all',
  );
  // Exported menu link: main-menu_diritto-di-famiglia:taxonomy/term/2072.
  $menu_links['main-menu_diritto-di-famiglia:taxonomy/term/2072'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/2072',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'diritto di famiglia',
    'options' => array(
      'identifier' => 'main-menu_diritto-di-famiglia:taxonomy/term/2072',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_famiglia:taxonomy/term/13/all',
  );
  // Exported menu link: main-menu_donna:taxonomy/term/22.
  $menu_links['main-menu_donna:taxonomy/term/22'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/22',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'donna',
    'options' => array(
      'identifier' => 'main-menu_donna:taxonomy/term/22',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_salute:taxonomy/term/21/all',
  );
  // Exported menu link: main-menu_donna:taxonomy/term/5/all.
  $menu_links['main-menu_donna:taxonomy/term/5/all'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/5/all',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'DONNA',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_donna:taxonomy/term/5/all',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_argomenti:<nolink>',
  );
  // Exported menu link: main-menu_essere-genitori:taxonomy/term/38.
  $menu_links['main-menu_essere-genitori:taxonomy/term/38'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/38',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'essere genitori',
    'options' => array(
      'identifier' => 'main-menu_essere-genitori:taxonomy/term/38',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_famiglia:taxonomy/term/13/all',
  );
  // Exported menu link: main-menu_eventi:events.
  $menu_links['main-menu_eventi:events'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'events',
    'router_path' => 'events',
    'link_title' => 'EVENTI',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_eventi:events',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_novita:<nolink>',
  );
  // Exported menu link: main-menu_famiglia:taxonomy/term/13/all.
  $menu_links['main-menu_famiglia:taxonomy/term/13/all'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/13/all',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'FAMIGLIA',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_famiglia:taxonomy/term/13/all',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_argomenti:<nolink>',
  );
  // Exported menu link: main-menu_festivit:taxonomy/term/104.
  $menu_links['main-menu_festivit:taxonomy/term/104'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/104',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'festività',
    'options' => array(
      'identifier' => 'main-menu_festivit:taxonomy/term/104',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_famiglia:taxonomy/term/13/all',
  );
  // Exported menu link: main-menu_figli:taxonomy/term/8/all.
  $menu_links['main-menu_figli:taxonomy/term/8/all'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/8/all',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'FIGLI',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_figli:taxonomy/term/8/all',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_argomenti:<nolink>',
  );
  // Exported menu link: main-menu_film:films.
  $menu_links['main-menu_film:films'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'films',
    'router_path' => 'films',
    'link_title' => 'FILM',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_film:films',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_novita:<nolink>',
  );
  // Exported menu link: main-menu_forum:http://www.mammeonline.net/phpBB3/.
  $menu_links['main-menu_forum:http://www.mammeonline.net/phpBB3/'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'http://www.mammeonline.net/phpBB3/',
    'router_path' => '',
    'link_title' => 'FORUM',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_forum:http://www.mammeonline.net/phpBB3/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: main-menu_gallery:<front>.
  $menu_links['main-menu_gallery:<front>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'GALLERY',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_gallery:<front>',
    ),
    'module' => 'menu',
    'hidden' => 1,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -36,
    'customized' => 1,
  );
  // Exported menu link: main-menu_gemelli:taxonomy/term/162.
  $menu_links['main-menu_gemelli:taxonomy/term/162'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/162',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'gemelli',
    'options' => array(
      'identifier' => 'main-menu_gemelli:taxonomy/term/162',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_figli:taxonomy/term/8/all',
  );
  // Exported menu link: main-menu_giovani-autori:taxonomy/term/83.
  $menu_links['main-menu_giovani-autori:taxonomy/term/83'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/83',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'giovani autori',
    'options' => array(
      'identifier' => 'main-menu_giovani-autori:taxonomy/term/83',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_figli:taxonomy/term/8/all',
  );
  // Exported menu link: main-menu_gravidanza:taxonomy/term/2.
  $menu_links['main-menu_gravidanza:taxonomy/term/2'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/2',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'gravidanza',
    'options' => array(
      'identifier' => 'main-menu_gravidanza:taxonomy/term/2',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_mamma:taxonomy/term/1/all',
  );
  // Exported menu link: main-menu_halloween:taxonomy/term/107.
  $menu_links['main-menu_halloween:taxonomy/term/107'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/107',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Halloween',
    'options' => array(
      'identifier' => 'main-menu_halloween:taxonomy/term/107',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_festivit:taxonomy/term/104',
  );
  // Exported menu link: main-menu_hobby:taxonomy/term/612.
  $menu_links['main-menu_hobby:taxonomy/term/612'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/612',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'hobby',
    'options' => array(
      'identifier' => 'main-menu_hobby:taxonomy/term/612',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_famiglia:taxonomy/term/13/all',
  );
  // Exported menu link: main-menu_home:node/6363.
  $menu_links['main-menu_home:node/6363'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/6363',
    'router_path' => 'node/%',
    'link_title' => 'HOME',
    'options' => array(
      'link_icon' => '',
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'main-menu_home:node/6363',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: main-menu_ibs:http://www.ibs.it/hmepge.asp?shop=1179.
  $menu_links['main-menu_ibs:http://www.ibs.it/hmepge.asp?shop=1179'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'http://www.ibs.it/hmepge.asp?shop=1179',
    'router_path' => '',
    'link_title' => 'IBS',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_ibs:http://www.ibs.it/hmepge.asp?shop=1179',
    ),
    'module' => 'menu',
    'hidden' => 1,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
  );
  // Exported menu link: main-menu_idee-regalo:taxonomy/term/1540.
  $menu_links['main-menu_idee-regalo:taxonomy/term/1540'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/1540',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Idee regalo',
    'options' => array(
      'identifier' => 'main-menu_idee-regalo:taxonomy/term/1540',
    ),
    'module' => 'menu',
    'hidden' => 1,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_speciale-natale:taxonomy/term/105',
  );
  // Exported menu link: main-menu_infertilit:taxonomy/term/12.
  $menu_links['main-menu_infertilit:taxonomy/term/12'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/12',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'infertilità',
    'options' => array(
      'identifier' => 'main-menu_infertilit:taxonomy/term/12',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_salute:taxonomy/term/21/all',
  );
  // Exported menu link: main-menu_la-moda-delle-feste:taxonomy/term/1542.
  $menu_links['main-menu_la-moda-delle-feste:taxonomy/term/1542'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/1542',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'La moda delle feste',
    'options' => array(
      'identifier' => 'main-menu_la-moda-delle-feste:taxonomy/term/1542',
    ),
    'module' => 'menu',
    'hidden' => 1,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_speciale-natale:taxonomy/term/105',
  );
  // Exported menu link: main-menu_lavoro-societ:taxonomy/term/16.
  $menu_links['main-menu_lavoro-societ:taxonomy/term/16'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/16',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'lavoro-società',
    'options' => array(
      'identifier' => 'main-menu_lavoro-societ:taxonomy/term/16',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_donna:taxonomy/term/5/all',
  );
  // Exported menu link: main-menu_letture:taxonomy/term/145.
  $menu_links['main-menu_letture:taxonomy/term/145'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/145',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'letture',
    'options' => array(
      'identifier' => 'main-menu_letture:taxonomy/term/145',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_mamma:taxonomy/term/1/all',
  );
  // Exported menu link: main-menu_letture:taxonomy/term/19.
  $menu_links['main-menu_letture:taxonomy/term/19'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/19',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'letture',
    'options' => array(
      'identifier' => 'main-menu_letture:taxonomy/term/19',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_figli:taxonomy/term/8/all',
  );
  // Exported menu link: main-menu_libri:books.
  $menu_links['main-menu_libri:books'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'books',
    'router_path' => 'books',
    'link_title' => 'LIBRI',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_libri:books',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_novita:<nolink>',
  );
  // Exported menu link: main-menu_login:user/login.
  $menu_links['main-menu_login:user/login'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'user/login',
    'router_path' => 'user/login',
    'link_title' => 'LOGIN',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_login:user/login',
    ),
    'module' => 'menu',
    'hidden' => 1,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -37,
    'customized' => 1,
  );
  // Exported menu link: main-menu_mamma:taxonomy/term/1/all.
  $menu_links['main-menu_mamma:taxonomy/term/1/all'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/1/all',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'MAMMA',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_mamma:taxonomy/term/1/all',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_argomenti:<nolink>',
  );
  // Exported menu link: main-menu_mamma:taxonomy/term/23.
  $menu_links['main-menu_mamma:taxonomy/term/23'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/23',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'mamma',
    'options' => array(
      'identifier' => 'main-menu_mamma:taxonomy/term/23',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_salute:taxonomy/term/21/all',
  );
  // Exported menu link: main-menu_moda:taxonomy/term/6.
  $menu_links['main-menu_moda:taxonomy/term/6'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/6',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'moda',
    'options' => array(
      'identifier' => 'main-menu_moda:taxonomy/term/6',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_donna:taxonomy/term/5/all',
  );
  // Exported menu link: main-menu_molfitness:taxonomy/term/2762.
  $menu_links['main-menu_molfitness:taxonomy/term/2762'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/2762',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'MOLFitness',
    'options' => array(
      'link_icon' => '',
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'main-menu_molfitness:taxonomy/term/2762',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_donna:taxonomy/term/5/all',
  );
  // Exported menu link: main-menu_natale:taxonomy/term/105.
  $menu_links['main-menu_natale:taxonomy/term/105'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/105',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Natale',
    'options' => array(
      'identifier' => 'main-menu_natale:taxonomy/term/105',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_festivit:taxonomy/term/104',
  );
  // Exported menu link: main-menu_naturopatia:taxonomy/term/388.
  $menu_links['main-menu_naturopatia:taxonomy/term/388'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/388',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'naturopatia',
    'options' => array(
      'identifier' => 'main-menu_naturopatia:taxonomy/term/388',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_salute:taxonomy/term/21/all',
  );
  // Exported menu link: main-menu_novita:<nolink>.
  $menu_links['main-menu_novita:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'NOVITA\'',
    'options' => array(
      'link_icon' => '',
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'main-menu_novita:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
  );
  // Exported menu link: main-menu_parto-e-post-partum:taxonomy/term/3.
  $menu_links['main-menu_parto-e-post-partum:taxonomy/term/3'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/3',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'parto e post partum',
    'options' => array(
      'identifier' => 'main-menu_parto-e-post-partum:taxonomy/term/3',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_mamma:taxonomy/term/1/all',
  );
  // Exported menu link: main-menu_pasqua:taxonomy/term/106.
  $menu_links['main-menu_pasqua:taxonomy/term/106'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/106',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Pasqua',
    'options' => array(
      'identifier' => 'main-menu_pasqua:taxonomy/term/106',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_festivit:taxonomy/term/104',
  );
  // Exported menu link: main-menu_psicologia-evolutiva:taxonomy/term/20.
  $menu_links['main-menu_psicologia-evolutiva:taxonomy/term/20'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/20',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'psicologia evolutiva',
    'options' => array(
      'identifier' => 'main-menu_psicologia-evolutiva:taxonomy/term/20',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_salute:taxonomy/term/21/all',
  );
  // Exported menu link: main-menu_psicologia:taxonomy/term/144.
  $menu_links['main-menu_psicologia:taxonomy/term/144'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/144',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'psicologia',
    'options' => array(
      'identifier' => 'main-menu_psicologia:taxonomy/term/144',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_salute:taxonomy/term/21/all',
  );
  // Exported menu link: main-menu_redazione:node/197.
  $menu_links['main-menu_redazione:node/197'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/197',
    'router_path' => 'node/%',
    'link_title' => 'REDAZIONE',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_redazione:node/197',
    ),
    'module' => 'menu',
    'hidden' => 1,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_chi-siamo:node/220',
  );
  // Exported menu link: main-menu_salute:taxonomy/term/21/all.
  $menu_links['main-menu_salute:taxonomy/term/21/all'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/21/all',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'SALUTE',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_salute:taxonomy/term/21/all',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_argomenti:<nolink>',
  );
  // Exported menu link: main-menu_solidariet:taxonomy/term/210.
  $menu_links['main-menu_solidariet:taxonomy/term/210'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/210',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'solidarietà',
    'options' => array(
      'identifier' => 'main-menu_solidariet:taxonomy/term/210',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_donna:taxonomy/term/5/all',
  );
  // Exported menu link: main-menu_speciale-natale:taxonomy/term/105.
  $menu_links['main-menu_speciale-natale:taxonomy/term/105'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/105',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'SPECIALE NATALE',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_speciale-natale:taxonomy/term/105',
    ),
    'module' => 'menu',
    'hidden' => 1,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: main-menu_storie-di-adozione:taxonomy/term/11.
  $menu_links['main-menu_storie-di-adozione:taxonomy/term/11'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/11',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'storie di adozione',
    'options' => array(
      'identifier' => 'main-menu_storie-di-adozione:taxonomy/term/11',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_adozione:taxonomy/term/9',
  );
  // Exported menu link: main-menu_storie-di-mamme:taxonomy/term/25.
  $menu_links['main-menu_storie-di-mamme:taxonomy/term/25'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/25',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'storie di mamme',
    'options' => array(
      'identifier' => 'main-menu_storie-di-mamme:taxonomy/term/25',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_mamma:taxonomy/term/1/all',
  );
  // Exported menu link: main-menu_svezzamento:taxonomy/term/62.
  $menu_links['main-menu_svezzamento:taxonomy/term/62'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/62',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'svezzamento',
    'options' => array(
      'identifier' => 'main-menu_svezzamento:taxonomy/term/62',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_mamma:taxonomy/term/1/all',
  );
  // Exported menu link: main-menu_tutto-adozione:taxonomy/term/10.
  $menu_links['main-menu_tutto-adozione:taxonomy/term/10'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/10',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'tutto adozione',
    'options' => array(
      'identifier' => 'main-menu_tutto-adozione:taxonomy/term/10',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_adozione:taxonomy/term/9',
  );
  // Exported menu link: secondary-menu_chi-siamo:node/220.
  $menu_links['secondary-menu_chi-siamo:node/220'] = array(
    'menu_name' => 'secondary-menu',
    'link_path' => 'node/220',
    'router_path' => 'node/%',
    'link_title' => 'chi siamo',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'secondary-menu_chi-siamo:node/220',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: secondary-menu_contatto:contact.
  $menu_links['secondary-menu_contatto:contact'] = array(
    'menu_name' => 'secondary-menu',
    'link_path' => 'contact',
    'router_path' => 'contact',
    'link_title' => 'contatto',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'secondary-menu_contatto:contact',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: secondary-menu_logout:user/logout.
  $menu_links['secondary-menu_logout:user/logout'] = array(
    'menu_name' => 'secondary-menu',
    'link_path' => 'user/logout',
    'router_path' => 'user/logout',
    'link_title' => 'logout',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'secondary-menu_logout:user/logout',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: secondary-menu_privacy:node/6203.
  $menu_links['secondary-menu_privacy:node/6203'] = array(
    'menu_name' => 'secondary-menu',
    'link_path' => 'node/6203',
    'router_path' => 'node/%',
    'link_title' => 'privacy',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'secondary-menu_privacy:node/6203',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: secondary-menu_redazione:node/197.
  $menu_links['secondary-menu_redazione:node/197'] = array(
    'menu_name' => 'secondary-menu',
    'link_path' => 'node/197',
    'router_path' => 'node/%',
    'link_title' => 'redazione',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'secondary-menu_redazione:node/197',
    ),
    'module' => 'menu',
    'hidden' => 1,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'secondary-menu_chi-siamo:node/220',
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('0-12 mesi');
  t('1-3 anni');
  t('3-5 anni');
  t('6-10 anni');
  t('ARGOMENTI');
  t('BLOG');
  t('CERCA');
  t('CHI SIAMO');
  t('CONTATTO');
  t('Calendario dell\'Avvento');
  t('Creatività Natale');
  t('Cucina in festa');
  t('DONNA');
  t('EVENTI');
  t('FAMIGLIA');
  t('FIGLI');
  t('FILM');
  t('FORUM');
  t('GALLERY');
  t('HOME');
  t('Halloween');
  t('IBS');
  t('Idee regalo');
  t('LIBRI');
  t('LOGIN');
  t('La moda delle feste');
  t('MAMMA');
  t('MOLFitness');
  t('NOVITA\'');
  t('Natale');
  t('Pasqua');
  t('REDAZIONE');
  t('SALUTE');
  t('SPECIALE NATALE');
  t('adolescenza');
  t('adozione');
  t('alimentazione');
  t('allattamento');
  t('archivio moda');
  t('bambino');
  t('bellezza');
  t('casa');
  t('chi siamo');
  t('compleanni');
  t('contatto');
  t('coppia');
  t('creatività');
  t('cucina');
  t('diritto di famiglia');
  t('donna');
  t('essere genitori');
  t('festività');
  t('gemelli');
  t('giovani autori');
  t('gravidanza');
  t('hobby');
  t('infertilità');
  t('lavoro-società');
  t('letture');
  t('logout');
  t('mamma');
  t('moda');
  t('naturopatia');
  t('parto e post partum');
  t('privacy');
  t('psicologia');
  t('psicologia evolutiva');
  t('redazione');
  t('solidarietà');
  t('storie di adozione');
  t('storie di mamme');
  t('svezzamento');
  t('tutto adozione');

  return $menu_links;
}
